apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: build
spec:
  params:
    - name: TLSVERIFY
      default: "false"
      description: Verify the TLS on the registry endpoint
      type: string
    - name: STORAGE_DRIVER
      description: The Buildah storage STORAGE_DRIVER
      type: string
    - name: app-dir
      type: string
  stepTemplate:
    env:
      - name: "HOME"
        value: "/tekton/home"
  steps:
    - name: package-node-app
      command:
      - /bin/sh
      - -c
      args:
      - |-
        npm install -g npm@9.2.0
        npm install
        ls -al
      image: image-registry.openshift-image-registry.svc:5000/$(context.taskRun.namespace)/rhel9-nodejs-16:latest
      resources: {}
      workingDir: /resources/$(params.app-dir)
    - name: build
      command:
      - buildah
      - bud
      - --tls-verify=$(params.TLSVERIFY)
      - --storage-driver=$(params.STORAGE_DRIVER)
      - --root
      - /files/buildah-containers
      - --layers
      - -f
      - ./dockerfile
      - -t
      - my-container-image
      - .
      image: image-registry.openshift-image-registry.svc:5000/$(context.taskRun.namespace)/buildah:latest
      resources: {}
      securityContext:
        capabilities:
          add:
          - SETFCAP
      workingDir: /resources/$(params.app-dir)
    - name: list-images
      command:
      - buildah
      - images
      - --storage-driver=$(params.STORAGE_DRIVER)
      - --root
      - /files/buildah-containers
      image: image-registry.openshift-image-registry.svc:5000/$(context.taskRun.namespace)/buildah:latest
      resources: {}
      securityContext:
        capabilities:
          add:
          - SETFCAP
      workingDir: /
  volumes:
    - emptyDir: {}
      name: envparams
  workspaces:
    - mountPath: /files
      name: files
    - mountPath: /resources
      name: resources

