apiVersion: triggers.tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: pacman1-ci-pipeline-listener-interceptor
spec:
  serviceAccountName: pipeline
  triggers:
  - name: github-listener
    interceptors:
      - ref:
          name: "github"
          kind: ClusterInterceptor
          apiVersion: triggers.tekton.dev
        params:
        - name: "addChangedFiles"
          value:
            enabled: true
      - ref:
          name: cel
        params:
        - name: "filter"
          value: 'header.match("X-GitHub-Event", "push") && extensions.changed_files.matches("src")'    
        - name: "overlays"
          value:
          - key: branch
            expression: "body.ref.split('/')[2]"
    bindings:
      - ref: pacman1-ci-binding
    template:
      ref: pacman1-ci-template
